### ISSUE TITLE
Can't require p4api after install

### ISSUE THREAD

**Issue by rightson** [Pisamad/p4api#1]
% node --version          
v8.11.2

% npm --version           
5.6.0

% npm install p4api --save
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN perforce No description
npm WARN perforce No repository field.
npm WARN perforce No license field.

+ p4api@3.0.0
removed 2 packages and updated 19 packages in 1.68s

% node
> let { P4 } = require('p4api')
Error: Cannot find module 'p4api'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
>

Do you have any suggestion about above usage?

**Comment by Pisamad** [comment]
I will check my config asap this week ...

**Comment by Pisamad** [comment]
My apologies, it's a package generator error.
A quick fix consists to modify the line #64 in node_modules/p4api/package.json 
  "main": "lib/library.js",        -->   "main": "lib/p4api.js",

I will upgrade the npm version in the week ...

**Comment by Pisamad** [comment]
Fix on V3.0.1
