### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object

### ISSUE THREAD

**Issue by cope** [Pisamad/p4api#10]
I keep getting this error:
```
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:219:9)
    at convertOut (C:\git\myproject\node_modules\p4api\lib\p4api.js:23971:87)
    at P4.cmdSync (C:\git\myproject\node_modules\p4api\lib\p4api.js:17952:840)
    at Perforce.getChangelist (C:\git\myproject\src\lib\perforce.js:124:27)
    at Args.parse (C:\git\myproject\src\lib\args.js:84:30)
    at start (C:\git\myproject\main.js:42:23)
    at App.checkP4Config (C:\git\myproject\main.js:71:10)
    at App.emit (events.js:205:15)
```

which really makes no sense because the command I am making is:
```
var cmd = "changes -m1 -s submitted C:/Perforce/...#have";
p4.cmdSync(cmd);
```

So, I'm clearly passing a string, which makes the error very confusing :(

**Comment by Pisamad** [comment]
Hi cope,
you are right, it's confusing.
The error is not concerning your command but the result which should be a string ...
I did not succeed in reproducing this issue in my context.
Could you tell me the Nodejs version you use ?

In your app, do you have other commands p4.cmd or cmdSync successfull or failed ?

**Comment by cope** [comment]
Hi Pisamad, thanks for a quick response.

Node: v8.15.0
NPM; v6.4.1

That was a good question, because I do and they all seem to have the same error now - even though they definitely worked before :(

Now I am actually more confused than before :(

I will create some tests for me locally now, to see if the problem is maybe on my end.

**Comment by cope** [comment]
And yes, the problem was on my side :(

Somehow, p4 was gone from my path :(

Sorry to have bothered you!

**Comment by Pisamad** [comment]
Hi Cope,
OK, I understand the problem better and I can reproduce it now. :-)
We can also consider the problem from my side! It's bad management of an exception.
I will work on it for the next version.
Thanks for your feedback.

**Comment by janupan** [comment]
So what the solution @Pisamad @cope

**Comment by cope** [comment]
@janupan :
![image](https://user-images.githubusercontent.com/112515/75967458-1f519100-5ecc-11ea-97af-4a8c981ffab5.png)

**Comment by Pisamad** [comment]
Hi @janupan ,

The problem raised by the @cope came from an unhandled exception when the p4 application was inaccessible.
So I treated this case by raising an exception of type P4.Error.

See readme.md :
_Error handling
If p4 client can not be executed (perforce not installed, bad path variable, ...), cmd is rejected and cmdSync is throwed with a P4.Error Error instance._
