### ISSUE TITLE
Publish latest changes to npm

### ISSUE THREAD

**Issue by LiamBest** [Pisamad/p4api#13]
Hey there, is there any chance you could publish latest to npm? I was hoping to pull down my binary path change from December into a project.

**Comment by Pisamad** [comment]
Hello,
Sorry for this late answer. I was working on other projects.
Of course, I can produce a new release to npm. 
Let me some days to check the current state, then I will update release to npm.

**Comment by Pisamad** [comment]
V3.4.0 is published
