### ISSUE TITLE
Please specify a license for this project

### ISSUE THREAD

**Issue by nlfiedler** [Pisamad/p4api#2]
Without a specific license for this project, it is difficult for others to use, legally. Could you please choose one and update the README and `package.json` file appropriately (and probably add a `LICENSE.txt` file as well). Thank you for writing this very useful library.

**Comment by Pisamad** [comment]
Glad to see that my work interests someone ! :-)
OK, I will add a licence. I will take time to do that for before next Monday.

**Comment by Pisamad** [comment]
It's done.

**Comment by nlfiedler** [comment]
Terrific, thank you.
